plugins {
    id "org.jetbrains.intellij.platform" version "2.19.0"
    id 'java'
}

group 'com.linuxgods.kreiger.idea'
version '1.2.1'

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdea "2023.3"
    }
}

intellijPlatformTesting.runIde.register("runLatestIde") {
    type = org.jetbrains.intellij.platform.gradle.IntelliJPlatformType.IntellijIdea
    version = "latest"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}
